In [26]:
import numpy as np

In [ ]:
#NUMPY INDEXING AND SLICING OF VECTORS

In [10]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr[9]

20

In [20]:
arr[1:5]

array([12, 13, 14, 15])

In [21]:
arr[2::3]

array([13, 16, 19])

In [28]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [30]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [44]:
slice = arr[3: , 3:]
slice 

array([[19, 20],
       [24, 25],
       [29, 30]])