In [5]:
import numpy as np

In [ ]:
#NUMPY INDEXING AND SLICING OF VECTORS

In [10]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr[9]

20

In [20]:
arr[1:5]

array([12, 13, 14, 15])

In [21]:
arr[2::3]

array([13, 16, 19])