In [2]:
import numpy as np

In [12]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1,2,3,4.5]
a

[1, 2, 3, 4.5]

In [15]:
np.array(a)

array([1. , 2. , 3. , 4.5])

In [17]:
k = [[1,2,3], [4,5,6], [7,8,9]]

In [18]:
np.array(k)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
arr = np.full((2,2),2)
arr

array([[2, 2],
       [2, 2]])

In [14]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [18]:
# Random number generation

In [23]:
np.random.rand(10)

array([0.96816254, 0.33764454, 0.2691781 , 0.50921404, 0.4177615 ,
       0.06885979, 0.79252474, 0.86567286, 0.81702353, 0.55037922])

In [29]:
np.random.randn(10)

array([-0.92248817, -1.02487999,  1.43286726, -1.12260312,  1.29192847,
        0.93326806, -0.55768039, -0.88846077,  0.23401085,  0.44027162])

In [35]:
np.random.randint(9 , 19, 10)

array([15, 14, 12,  9, 13, 17, 10, 15, 11, 13])

In [ ]:
# Array Attributes

In [61]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.shape

(3, 3)

In [43]:
arr.size

9

In [44]:
arr.dtype

dtype('int64')

In [46]:
arr.min()

1

In [47]:
arr.max()

9

In [48]:
arr.sum()

45

In [63]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [64]:
arr.mean()

5.0

In [65]:
arr.std()

2.581988897471611

In [66]:
arr.argmax()

8

In [67]:
arr.argmin()

0

In [ ]:
# Reshaping and resizing     

In [71]:
arr = np.arange(1,41)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [73]:
arr.reshape(5,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])